// ============================================================
// src/lib/rag.ts — Cosine similarity search for RAG
// Used by: src/app/api/chat/route.ts
// Reads: data/embeddings.json (generated by generate-embeddings.ts)
// ============================================================

import * as fs from "fs";
import * as path from "path";

interface EmbeddingEntry {
  id: string;
  category: string;
  content: string;
  embedding: number[];
}

// Cosine similarity between two vectors
function cosineSimilarity(a: number[], b: number[]): number {
  let dot = 0;
  let magA = 0;
  let magB = 0;

  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    magA += a[i] * a[i];
    magB += b[i] * b[i];
  }

  const magnitude = Math.sqrt(magA) * Math.sqrt(magB);
  return magnitude === 0 ? 0 : dot / magnitude;
}

// Load embeddings once and cache in memory
let cachedEmbeddings: EmbeddingEntry[] | null = null;

function loadEmbeddings(): EmbeddingEntry[] {
  if (cachedEmbeddings) return cachedEmbeddings;

  const embeddingsPath = path.resolve(process.cwd(), "data", "embeddings.json");

  if (!fs.existsSync(embeddingsPath)) {
    console.warn(
      "[rag] data/embeddings.json not found. " +
        "Run: npx tsx data/scripts/generate-embeddings.ts",
    );
    return [];
  }

  cachedEmbeddings = JSON.parse(
    fs.readFileSync(embeddingsPath, "utf-8"),
  ) as EmbeddingEntry[];

  return cachedEmbeddings;
}

// Get embedding vector for a query string
async function getQueryEmbedding(query: string): Promise<number[]> {
  const { default: OpenAI } = await import("openai");
  const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

  const response = await openai.embeddings.create({
    model: "text-embedding-3-small",
    input: query,
  });

  return response.data[0].embedding;
}

// Search embeddings and return top K chunks as plain text
export async function searchEmbeddings(
  query: string,
  topK = 3,
): Promise<string> {
  const embeddings = loadEmbeddings();

  // Fallback: no embeddings available
  if (!embeddings.length) {
    return "No context available. Please use the contact form for details.";
  }

  const queryVector = await getQueryEmbedding(query);

  // Score all chunks by cosine similarity
  const scored = embeddings.map((entry) => ({
    content: entry.content,
    similarity: cosineSimilarity(queryVector, entry.embedding),
  }));

  // Sort descending, take top K
  scored.sort((a, b) => b.similarity - a.similarity);
  const top = scored.slice(0, topK);

  return top.map((r) => r.content).join("\n\n");
}
