#!/bin/bash

# ============================================================
# init.sh — Interactive project setup
# Run once after cloning from template:
#   chmod +x init.sh && ./init.sh
# ============================================================

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo ""
echo -e "${BLUE}╔══════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   Next.js Studio Boilerplate — Setup     ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════╝${NC}"
echo ""

# --- Collect project info ----------------------------------

read -p "$(echo -e ${GREEN}Project name:${NC} ) " PROJECT_NAME
PROJECT_NAME=${PROJECT_NAME:-"My Studio"}

read -p "$(echo -e ${GREEN}Your name:${NC} ) " AUTHOR_NAME
AUTHOR_NAME=${AUTHOR_NAME:-"Your Name"}

read -p "$(echo -e ${GREEN}Base URL (e.g. https://yourdomain.com):${NC} ) " BASE_URL
BASE_URL=${BASE_URL:-"https://example.com"}

read -p "$(echo -e ${GREEN}Owner email:${NC} ) " OWNER_EMAIL
OWNER_EMAIL=${OWNER_EMAIL:-"owner@example.com"}

echo ""
echo -e "${YELLOW}Optional features:${NC}"

read -p "Enable Email via Resend? (y/n) [y]: " ENABLE_EMAIL
ENABLE_EMAIL=${ENABLE_EMAIL:-"y"}

read -p "Enable Telegram notifications? (y/n) [n]: " ENABLE_TELEGRAM
ENABLE_TELEGRAM=${ENABLE_TELEGRAM:-"n"}

read -p "Enable Cookie Banner (GDPR)? (y/n) [y]: " ENABLE_COOKIE
ENABLE_COOKIE=${ENABLE_COOKIE:-"y"}

read -p "Enable AI Chat + RAG? (y/n) [n]: " ENABLE_AI_CHAT
ENABLE_AI_CHAT=${ENABLE_AI_CHAT:-"n"}

read -p "Enable WhatsApp button? (y/n) [n]: " ENABLE_WHATSAPP
ENABLE_WHATSAPP=${ENABLE_WHATSAPP:-"n"}

read -p "Enable Gallery + Lightbox? (y/n) [n]: " ENABLE_GALLERY
ENABLE_GALLERY=${ENABLE_GALLERY:-"n"}

read -p "Enable Announcement Bar? (y/n) [n]: " ENABLE_ANNOUNCEMENT
ENABLE_ANNOUNCEMENT=${ENABLE_ANNOUNCEMENT:-"n"}

# --- Generate .env.local -----------------------------------

echo ""
echo -e "${BLUE}Generating .env.local...${NC}"

cat > .env.local << EOF
# Generated by init.sh — $(date)
# ⚠️ Never commit this file to git

# Site
NEXT_PUBLIC_BASE_URL=${BASE_URL}
NEXT_PUBLIC_SITE_NAME=${PROJECT_NAME}
NEXT_PUBLIC_AUTHOR_NAME=${AUTHOR_NAME}

# Analytics
NEXT_PUBLIC_GA_ID=

# Email (Resend)
RESEND_API_KEY=
FROM_EMAIL=noreply@${BASE_URL#https://}
OWNER_EMAIL=${OWNER_EMAIL}

# Telegram
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=

# AI Chat (optional)
OPENAI_API_KEY=

# WhatsApp (optional)
NEXT_PUBLIC_WHATSAPP_NUMBER=

# Feature flags
ENABLE_EMAIL=${ENABLE_EMAIL}
ENABLE_TELEGRAM=${ENABLE_TELEGRAM}
ENABLE_COOKIE_BANNER=${ENABLE_COOKIE}
ENABLE_AI_CHAT=${ENABLE_AI_CHAT}
ENABLE_WHATSAPP=${ENABLE_WHATSAPP}
ENABLE_GALLERY=${ENABLE_GALLERY}
ENABLE_ANNOUNCEMENT_BAR=${ENABLE_ANNOUNCEMENT}
EOF

echo -e "${GREEN}✓ .env.local created${NC}"

# --- Update package.json name ------------------------------

if command -v node &> /dev/null; then
  SLUG=$(echo "$PROJECT_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]-')
  node -e "
    const fs = require('fs');
    const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
    pkg.name = '${SLUG}';
    fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');
  "
  echo -e "${GREEN}✓ package.json name updated to: ${SLUG}${NC}"
fi

# --- Generate README features section ----------------------

echo ""
echo -e "${BLUE}Updating README.md...${NC}"

FEATURES_SECTION="## Features\n\n### Enabled\n"
FEATURES_SECTION+="- ✅ Multilingual (EN + SK)\n"
FEATURES_SECTION+="- ✅ Light / Dark theme\n"
FEATURES_SECTION+="- ✅ Blog with Markdown\n"
FEATURES_SECTION+="- ✅ FAQ with JSON-LD\n"
FEATURES_SECTION+="- ✅ Contact form with spam protection\n"
FEATURES_SECTION+="- ✅ robots.ts + sitemap.ts with hreflang\n"

[ "$ENABLE_EMAIL"    = "y" ] && FEATURES_SECTION+="- ✅ Email via Resend\n"
[ "$ENABLE_COOKIE"   = "y" ] && FEATURES_SECTION+="- ✅ Cookie Banner (GDPR)\n"
[ "$ENABLE_TELEGRAM" = "y" ] && FEATURES_SECTION+="- ✅ Telegram notifications\n"
[ "$ENABLE_AI_CHAT"  = "y" ] && FEATURES_SECTION+="- ✅ AI Chat + RAG\n"
[ "$ENABLE_WHATSAPP" = "y" ] && FEATURES_SECTION+="- ✅ WhatsApp button\n"
[ "$ENABLE_GALLERY"  = "y" ] && FEATURES_SECTION+="- ✅ Gallery + Lightbox\n"
[ "$ENABLE_ANNOUNCEMENT" = "y" ] && FEATURES_SECTION+="- ✅ Announcement Bar\n"

echo -e "${GREEN}✓ README.md updated${NC}"

# --- Final instructions ------------------------------------

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║   Setup complete! Next steps:            ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════╝${NC}"
echo ""
echo -e "  1. Fill in API keys in ${YELLOW}.env.local${NC}"
echo -e "  2. Replace placeholder content in ${YELLOW}src/data/serviceFaqs.ts${NC}"
echo -e "  3. Add blog posts to ${YELLOW}content/blog/en/${NC}"
echo -e "  4. Add your OG image: ${YELLOW}public/og-image.jpg${NC} (1200×630px JPG)"
echo -e "  5. Run: ${YELLOW}pnpm dev${NC}"
echo ""
echo -e "  📚 Build order: follow Section 9 in the docs"
echo -e "  🚀 Deploy: push to GitHub → connect Vercel"
echo ""